spring:
  application:
    name: EducationTrackingSystemApplication


  datasource:
    url: jdbc:mysql://localhost:3306/eduDB?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      dd-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

super_admin:
  email: ${SUPER_ADMIN_EMAIL}